### ISSUE TITLE
Update Express / Most middleware (like favicon) is no longer bundled with Express

### ISSUE THREAD

**Issue by tnguyen42** [aseemk/node-neo4j-template#22]
Hi,

I know that's an all project but you're still featured by Neo4J, so here I am :smile: 

When typing `npm start` after installing every packages and neo4j, this error occurs:

```
Most middleware (like favicon) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/Users/tnguyen/tutorials/Neo4JTemplate/node_modules/express/lib/express.js:99:13)
    at Object.<anonymous> (/Users/tnguyen/tutorials/Neo4JTemplate/app.js:17:16)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.nodeDevHook [as .js] (/Users/tnguyen/tutorials/Neo4JTemplate/node_modules/node-dev/lib/hook.js:43:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tnguyen/tutorials/Neo4JTemplate/node_modules/node-dev/lib/wrap.js:58:1)
```

I guess a little update is just required.

**Comment by aseemk** [comment]
Thanks for the heads-up!

Sounds like we need to update this app to a newer Express.

I'll see when I can get time to get to this, but I've labeled this pull-requests-welcome in the meantime. =)
